### PR TITLE
Tailwind setup updates

### PR DESCRIPTION
**Pull request by MrSep01**

### CODE REVIEW

**Review by RG-GitUser — APPROVED** [review]

**Review by RG-GitUser — CHANGES_REQUESTED** [review]
@MrSep01 unresolved issues

**Comment by RG-GitUser** [comment]
@MrSep01 Merged is blocked on this as well

**Comment by HuiPan-Peter** [comment]
taiwinds

**Review by HuiPan-Peter — APPROVED** [review]

**Comment by HuiPan-Peter** [comment]
tailwind

**Review by HuiPan-Peter — APPROVED** [review]

**Review by HuiPan-Peter — APPROVED** [review]

**Review by RG-GitUser — APPROVED** [review]

**Pull request merged**
